### ISSUE TITLE
Can not run !

### ISSUE THREAD

**Issue by andrewgf988** [somiibo/tiktok-bot#2]
i've install npm but then start not working. 
C:\Users\nguye\OneDrive\Desktop\tiktok-bot-main>pip install registry
Collecting registry
  Downloading registry-0.4.2.zip (11 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: registry
  Building wheel for registry (setup.py) ... done
  Created wheel for registry: filename=registry-0.4.2-py3-none-any.whl size=6724 sha256=152d1f8b6c90d4ec8f929c03158ed191ebd99bd0064a51dba94888b3a0072238
  Stored in directory: c:\users\nguye\appdata\local\pip\cache\wheels\42\83\70\93f42c59e44bbfbea7a2995bd453fa30e7131101eba5d08673
Successfully built registry
Installing collected packages: registry
Successfully installed registry-0.4.2

C:\Users\nguye\OneDrive\Desktop\tiktok-bot-main>npm start
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> somiibo-downloader@1.0.0 start
> node src/index.js

node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'registry-js'
Require stack:
- C:\Users\nguye\OneDrive\Desktop\tiktok-bot-main\node_modules\downloads-folder\index.js
- C:\Users\nguye\OneDrive\Desktop\tiktok-bot-main\src\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.windows [as win32] (C:\Users\nguye\OneDrive\Desktop\tiktok-bot-main\node_modules\downloads-folder\index.js:43:20)
    at module.exports (C:\Users\nguye\OneDrive\Desktop\tiktok-bot-main\node_modules\downloads-folder\index.js:14:19)
    at Module.module.exports (C:\Users\nguye\OneDrive\Desktop\tiktok-bot-main\src\index.js:14:30)
    at Object.<anonymous> (C:\Users\nguye\OneDrive\Desktop\tiktok-bot-main\src\index.js:50:10)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\nguye\\OneDrive\\Desktop\\tiktok-bot-main\\node_modules\\downloads-folder\\index.js',
    'C:\\Users\\nguye\\OneDrive\\Desktop\\tiktok-bot-main\\src\\index.js'
  ]
}

**Comment by 1x6** [comment]
lol

**Comment by IncognitoWelt** [comment]
lol

**Comment by LoveryBryan** [comment]
not found
