### ISSUE TITLE
Error: Cannot find module 'registry-js'

### ISSUE THREAD

**Issue by Za99GamerBR** [somiibo/tiktok-bot#3]
Error: Cannot find module 'registry-js'
Require stack:
- C:\Users\Administrador\Desktop\tiktok-bot-main\node_modules\downloads-folder\index.js
- C:\Users\Administrador\Desktop\tiktok-bot-main\src\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.windows [as win32] (C:\Users\Administrador\Desktop\tiktok-bot-main\node_modules\downloads-folder\index.js:43:20)
    at module.exports (C:\Users\Administrador\Desktop\tiktok-bot-main\node_modules\downloads-folder\index.js:14:19)
    at module.exports (C:\Users\Administrador\Desktop\tiktok-bot-main\src\index.js:14:30)
    at Object.<anonymous> (C:\Users\Administrador\Desktop\tiktok-bot-main\src\index.js:50:10)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrador\\Desktop\\tiktok-bot-main\\node_modules\\downloads-folder\\index.js',
    'C:\\Users\\Administrador\\Desktop\\tiktok-bot-main\\src\\index.js'
  ]
}

Node.js v18.17.1

**Comment by buwads288** [comment]
yup same as me how can fix this

**Comment by pee111** [comment]
here also...
